### ISSUE TITLE
Many false postives for "remove unused method"

### ISSUE THREAD

**Issue by PragTob** [flyerhzm/rails_best_practices#102]
Hey there,

at first thanks for rails best practices - very cool tool.
When running the tool on my project [Tracketytrack](https://github.com/PragTob/TracketyTrack) I seem to get many false positives telling me to remove unused methods, however these methods are used. 
For instance:

```
./app/models/user.rb:75 - remove unused methods (User#make_salt)
```

where the method is definitely used (extracted from user.rb:)

``` ruby
def encrypt_password
  self.salt = make_salt if new_record?
  self.encrypted_password = encrypt(password) unless password.blank?
end

def encrypt(string)
  secure_hash("#{salt}--#{string}")
end

def make_salt
  secure_hash("#{Time.now.utc}--#{password}")
end
```

make_salt is used right at line 2. 

For all the methods that are claimed to be unused check [this gist](https://gist.github.com/1861498) - I can't guarantee right now that all of them are really used but the majority totally is (otherwise shame on me and my team!). But every method I checked so far is used and some of them pretty essential :-)

Oh I'm using 1.7.2.

Thank you!

**Comment by nroose** [comment]
I know I am late to this game, but I just cleaned up 9 of these in one of our apps, with the latest rbp.  One was a scope that was only used in another scope.  I ended up just putting that code into one scope.  Three were due to complex routes that I would love to remove but there does not seem to be a way to maintain support for our routes - we have 3 controller get methods and when a user does the get, it looks like a show with the action name as the id, rather than the controller method.  Surely we need to fix that, but not sure how yet.  So I added them to the except array.  The 5 other unused ones were actually unused!  I guess those funny routes don't need to be fixed in rbp, but perhaps a scope that is used in another scope is legit, to keep the other scope simple.

**Comment by ignacio-chiazzo** [comment]
I have the same issue.
 
In #show method of my LocationController I have a helper method. Something like 

`class LocationsController < ApiController
      helper_method :particular_method`

The helper_method ':particular_method' is not used in the controller, nonetheless, the helper method is used inside some views and I am getting the warning: 

> remove unused methods (LocationsController#particular_method)

**Comment by sebs** [comment]
Same for me, gonna disable, to many false positives.

**Comment by hs-dliaska** [comment]
i got false positives for searchkick gem slug_candidates and search_data methods
